language: php

php:
  - 5.3
  - 5.4

before_script:
  - "sh -c 'curl -s http://getcomposer.org/installer | php'"
  - "sh -c 'php composer.phar install --quiet'"
  - chmod +x ./redis-driver-installer.sh
  - sh ./redis-driver-installer.sh

script: "sh -c 'php tests/Slamecka/RedisStorage.php'"

